import logo from './assets/img/logo-emblem.png'
import hero from './assets/img/hero-training.jpg'
import team from './assets/img/team-practical.jpg'
import careers from './assets/img/team-careers.jpg'
import office from './assets/img/office.jpg'
import classroom from './assets/img/classroom.jpg'
const im = (n) => new URL(`./assets/img/c-${n}.jpg`, import.meta.url).href
export const IMG = { logo, hero, team, careers, office, classroom }

// ✏️ Change these in one place
export const SITE = {
  whatsapp: import.meta.env.VITE_WHATSAPP_NUMBER || '250788698167',
  phones: [['0789 649 089', '+250789649089'], ['0788 698 167', '+250788698167']],
  place: 'Nyabyondo, Rulindo, Rwanda', seats: 10,
}
// ✏️ Fill in REAL values per course id; empty = not shown. Example: juice: { duration: '3 months', fee: '50,000 RWF' }
export const COURSE_INFO = {}
export const COURSES = [
  { id: 'hospitality', img: im('hospitality'),
    en: 'Hospitality & Customer Service',
    rw: 'Kwakira Abashyitsi na Serivisi',
    fr: 'Hôtellerie et Service Client',
    sw: 'Ukarimu na Huduma kwa Wateja',
    pts: {
      en: ['Guest care & relations', 'Professional etiquette', 'Hygiene & grooming'],
      rw: ['Kwakira abakiriya n\'abashyitsi', 'Imyitwarire myiza mu kazi', 'Isuku n\'imyambarire'],
      fr: ['Accueil et relation client', 'Savoir-être professionnel', 'Hygiène et présentation'],
      sw: ['Huduma kwa wageni na wateja', 'Adabu za kitaaluma', 'Usafi na mwonekano'],
    } },
  { id: 'fnb', img: im('fnb'),
    en: 'Food & Beverage Service',
    rw: 'Serivisi y\'Ibiribwa n\'Ibinyobwa',
    fr: 'Service Restauration et Boissons',
    sw: 'Huduma ya Chakula na Vinywaji',
    pts: {
      en: ['Table setting & serving', 'Bartending & barista skills', 'Catering basics'],
      rw: ['Gutegura ameza no gutanga serivisi', 'Bartending n\'ubumenyi bwa Barista', 'Gutegura ibiryo mu birori (Catering)'],
      fr: ['Dressage de table et service', 'Bartending et barista', 'Notions de traiteur'],
      sw: ['Kupanga meza na kuhudumia', 'Ubarmeni na ujuzi wa barista', 'Misingi ya upishi wa matukio (catering)'],
    } },
  { id: 'juice', img: im('juice'),
    en: 'Juice Making',
    rw: 'Gukora Juice n\'Ibinyobwa',
    fr: 'Fabrication de Jus',
    sw: 'Utengenezaji wa Juisi',
    pts: {
      en: ['Fresh juice & blending', 'Packaging & portion control', 'Costing & pricing'],
      rw: ['Gukora juice nshya', 'Gupakira no kugenzura ingano', 'Kubara ibiciro no gushyiraho igiciro'],
      fr: ['Jus frais et mélanges', 'Emballage et dosage des portions', 'Calcul des coûts et fixation des prix'],
      sw: ['Juisi safi na kuchanganya', 'Ufungashaji na vipimo vya sehemu', 'Kukokotoa gharama na bei'],
    } },
  { id: 'soap', img: im('soap'),
    en: 'Soap Making',
    rw: 'Gukora Isabune',
    fr: 'Fabrication de Savon',
    sw: 'Utengenezaji wa Sabuni',
    pts: {
      en: ['Soap & candle production', 'Safe handling & hygiene', 'Packaging & branding'],
      rw: ['Gukora isabune n\'amakandle', 'Isuku n\'umutekano mu kazi', 'Gupakira no kumenyekanisha ibicuruzwa'],
      fr: ['Fabrication de savon et de bougies', 'Manipulation sûre et hygiène', 'Emballage et image de marque'],
      sw: ['Kutengeneza sabuni na mishumaa', 'Utunzaji salama na usafi', 'Ufungashaji na chapa'],
    } },
  { id: 'computer', img: im('computer'),
    en: 'Computer',
    rw: 'Mudasobwa',
    fr: 'Informatique',
    sw: 'Kompyuta',
    pts: {
      en: ['Microsoft Word & Excel', 'Internet & email', 'Digital tools'],
      rw: ['Microsoft Word na Excel', 'Internet na Imeri', 'Ibikoresho bya digitale'],
      fr: ['Microsoft Word et Excel', 'Internet et e-mail', 'Outils numériques'],
      sw: ['Microsoft Word na Excel', 'Intaneti na barua pepe', 'Zana za kidijitali'],
    } },
  { id: 'photography', img: im('photography'),
    en: 'Photography',
    rw: 'Gufata Amafoto',
    fr: 'Photographie',
    sw: 'Upigaji Picha',
    pts: {
      en: ['Camera basics', 'Event photography', 'Photo editing'],
      rw: ['Ibanze bya kamera', 'Gufotora mu birori', 'Guhindura amafoto'],
      fr: ['Bases de la photographie', 'Photo d\'événements', 'Retouche photo'],
      sw: ['Misingi ya kamera', 'Upigaji picha wa matukio', 'Kuhariri picha'],
    } },
  { id: 'hairdressing', img: im('hairdressing'),
    en: 'Hairdressing',
    rw: 'Gutunganya Imisatsi',
    fr: 'Coiffure',
    sw: 'Mitindo ya Nywele',
    pts: {
      en: ['Styling & care', 'Salon hygiene', 'Customer service'],
      rw: ['Gutunganya no kwita ku misatsi', 'Isuku mu nzu y\'ubwiza (salon)', 'Kwakira abakiriya'],
      fr: ['Coiffure et soins', 'Hygiène du salon', 'Service client'],
      sw: ['Mitindo na utunzaji wa nywele', 'Usafi wa saluni', 'Huduma kwa wateja'],
    } },
  { id: 'languages', img: im('languages'),
    en: 'Languages',
    rw: 'Indimi',
    fr: 'Langues',
    sw: 'Lugha',
    pts: {
      en: ['English & Français', 'Hospitality vocabulary', 'Confident speaking'],
      rw: ['Icyongereza n\'Igifaransa', 'Amagambo akoreshwa mu bwakiranyi', 'Kuvuga nta bwoba'],
      fr: ['Anglais et français', 'Vocabulaire de l\'hôtellerie', 'Expression orale avec assurance'],
      sw: ['Kiingereza na Kifaransa', 'Msamiati wa ukarimu', 'Kuzungumza kwa kujiamini'],
    } },
  { id: 'pastry', img: im('pastry'),
    en: 'Pastry',
    rw: 'Gukora Keke n\'Ibiryo by\'Ifu',
    fr: 'Pâtisserie',
    sw: 'Keki na Maandazi',
    pts: {
      en: ['Cakes & cupcakes', 'Baking techniques', 'Selling your products'],
      rw: ['Keke na cupcakes', 'Uburyo bwo guteka (baking)', 'Kugurisha ibyo wakoze'],
      fr: ['Gâteaux et cupcakes', 'Techniques de pâtisserie', 'Vendre ses produits'],
      sw: ['Keki na cupcakes', 'Mbinu za kuoka', 'Kuuza bidhaa zako'],
    } },
  { id: 'life', img: im('career'),
    en: 'Life Skills & Personal Development',
    rw: 'Ubumenyi bw\'Ubuzima',
    fr: 'Compétences de Vie et Développement Personnel',
    sw: 'Stadi za Maisha na Maendeleo Binafsi',
    pts: {
      en: ['CV & interview skills', 'Work discipline', 'Business plan & savings'],
      rw: ['Gukora CV no kwitegura ikiganiro cy\'akazi', 'Discipline mu kazi', 'Gahunda y\'ubucuruzi no kuzigama'],
      fr: ['CV et entretien d\'embauche', 'Discipline au travail', 'Business plan et épargne'],
      sw: ['CV na usaili wa kazi', 'Nidhamu kazini', 'Mpango wa biashara na kuweka akiba'],
    } },
]
export const LANGS = [['en', 'EN', 'English'], ['fr', 'FR', 'Français'], ['rw', 'RW', 'Kinyarwanda'], ['sw', 'SW', 'Kiswahili']]
import { fr, sw } from './i18n-extra.js'
export const T = {
  en: {
    stats: ['Courses', 'Seats', 'Languages'], tagline: 'Learn Skills. Create Opportunities.', maps: 'Google Maps', hello: 'Hello PASCAL Academy, I would like more information.', feeAsk: 'Hello PASCAL Academy, please share the fees, duration and start date.', langLabel: 'Language',
    nav: ['Courses', 'Why PASCAL', 'Gallery', 'FAQ', 'Apply', 'Contact'], badge: 'First intake · Only 10 seats',
    dur: 'Duration', fee: 'Fee', feeNote: 'Fees, duration and start dates: message us on WhatsApp and we will share the current details.', feeBtn: 'Ask about fees',
    tap: 'Click to enlarge', close: 'Close', prev: 'Previous', next: 'Next', storiesT: 'Student Stories', storiesS: 'Hear from our students and graduates.', mapT: 'Find us on the map',
    faqT: 'Frequently Asked Questions', faqS: 'Quick answers before you apply.',
    faqs: [
      ['Where is PASCAL Academy located?', 'We are in Nyabyondo, Rulindo, Rwanda. You can find us on the map in the Contact section.'],
      ['How do I apply?', 'Fill in the application form on this page and press the WhatsApp button. Your application opens in WhatsApp, ready to send to our admissions team, who will reply to you.'],
      ['How many students are in the first intake?', 'The first intake is limited to only 10 students, so we encourage you to register early.'],
      ['Which courses do you offer?', 'Hospitality & Customer Service, Food & Beverage Service, Juice Making, Soap Making, Computer, Photography, Hairdressing, Languages, Pastry, and Life Skills & Personal Development. You can choose up to 3 on the form.'],
      ['Which languages can I learn?', 'We teach English and French, plus hospitality vocabulary and confident speaking.'],
      ['What will I gain?', 'Practical skills you can use immediately, a better chance of getting a job, the ability to start your own small business, and connections to opportunities.'],
      ['What are the fees, course duration and start date?', 'Classes start soon. Message or call us for the current fees, duration and start date.'],
    ],
    h1a: 'Skills for Today,', h1b: 'Opportunities for Tomorrow.', sub: 'Practical hospitality, food, digital and business training in Nyabyondo, Rulindo. Learn. Practice. Succeed.',
    cta1: 'Apply on WhatsApp', cta2: 'Explore courses', coursesT: 'Our 10 Courses', coursesS: 'Hands-on training designed to get you working or earning.', pick: 'Choose this course',
    whyT: 'Why PASCAL?', why: [['🎓', 'We Train', 'Practical skills you can use immediately'], ['🛠️', 'We Create', 'Real practice that builds small businesses'], ['🤝', 'We Connect', 'We link you with jobs & opportunities'], ['🌱', 'We Grow', 'Confidence, discipline and a business mindset']],
    gain: 'You will gain', gains: ['Practical skills', 'More chance to get a job', 'Start your own small business', 'Connections to opportunities'],
    galT: 'Life at PASCAL', applyT: 'Apply Now', applyS: 'Fill in the form — your application opens in WhatsApp, ready to send to our admissions team.',
    f: { name: 'Full name', gender: 'Gender', m: 'Male', fm: 'Female', dob: 'Date of birth', phone: 'WhatsApp / phone', email: 'Email (optional)', loc: 'District / Sector', edu: 'Education level', pickC: 'Courses you want (max 3)', msg: 'Message (optional)', consent: 'I agree to be contacted about my application.', send: 'Send application on WhatsApp', req: 'Required', badPhone: 'Use a valid Rwandan number e.g. 0788 123 456', pickOne: 'Select at least one course', ok: 'Application ready!', okS: 'WhatsApp should open. If not, tap the button below.', again: 'Open WhatsApp again', newApp: 'New application', ref: 'Reference' },
    edus: ['Primary', 'Ordinary Level (S1–S3)', 'Advanced Level (S4–S6)', 'TVET / Diploma', 'University', 'Other'],
    contactT: 'Visit or Contact Us', loc: 'Location', call: 'Call', rights: 'All rights reserved.', quote: 'Your future can start with one practical skill.' },
  rw: {
    stats: ['Amasomo', 'Imyanya', 'Indimi'], tagline: 'Ubumenyi bufatika. Amahirwe nyakuri.', maps: 'Google Maps', hello: 'Muraho PASCAL Academy, nifuza amakuru arambuye.', feeAsk: 'Muraho PASCAL Academy, nimumbwire amafaranga, igihe n’itariki yo gutangira.', langLabel: 'Ururimi',
    nav: ['Amasomo', 'Impamvu PASCAL', 'Amafoto', 'Ibibazo', 'Iyandikishe', 'Twandikire'], badge: 'Itangira rya mbere · Abanyeshuri 10 gusa',
    dur: 'Igihe', fee: 'Amafaranga', feeNote: 'Amafaranga, igihe n’amatariki yo gutangira: twandikire kuri WhatsApp tukubwire amakuru agezweho.', feeBtn: 'Baza ibiciro',
    tap: 'Kanda kugira ngo ubone neza', close: 'Funga', prev: 'Iyabanje', next: 'Ikurikira', storiesT: 'Ubuhamya bw’abanyeshuri', storiesS: 'Umva abanyeshuri bacu n’abarangije.', mapT: 'Aho tuherereye ku ikarita',
    faqT: 'Ibibazo bikunze kubazwa', faqS: 'Ibisubizo byihuse mbere yo kwiyandikisha.',
    faqs: [
      ['PASCAL Academy iherereye he?', 'Turi i Nyabyondo, Rulindo, mu Rwanda. Ushobora kutubona ku ikarita mu gice cyo Twandikire.'],
      ['Nakwiyandikisha nte?', 'Uzuza ifishi iri kuri uru rubuga ukande buto ya WhatsApp. Ubusabe bwawe bufungurwa kuri WhatsApp bwiteguye koherezwa, maze tukwandikire.'],
      ['Itangira rya mbere rizakira abanyeshuri bangahe?', 'Itangira rya mbere ni abanyeshuri 10 gusa, bityo wiyandikishe hakiri kare.'],
      ['Ni ayahe masomo mutanga?', 'Kwakira Abashyitsi na Serivisi, Serivisi y’Ibiribwa n’Ibinyobwa, Gukora Juice, Gukora Isabune, Mudasobwa, Gufata Amafoto, Gutunganya Imisatsi, Indimi, Pastry, n’Ubumenyi bw’Ubuzima. Ushobora guhitamo 3 ku ifishi.'],
      ['Ni izihe ndimi nakwiga?', 'Twigisha Icyongereza n’Igifaransa, hamwe n’amagambo akoreshwa mu bwakiranyi no kuvuga nta bwoba.'],
      ['Nzunguka iki?', 'Ubumenyi bufatika wakoresha ako kanya, amahirwe menshi yo kubona akazi, kwikorera, no guhuzwa n’amahirwe.'],
      ['Amafaranga, igihe n’itariki yo gutangira ni ibihe?', 'Amasomo azatangira vuba. Twandikire cyangwa uduhamagare tukubwire amakuru agezweho.'],
    ],
    h1a: 'Ubumenyi bufatika uyu munsi,', h1b: 'Ejo hazaza heza!', sub: 'Amahugurwa afatika mu bwakiranyi, ibiribwa, ikoranabuhanga n’ubucuruzi i Nyabyondo, Rulindo. Wiga. Witoze. Wahinduka.',
    cta1: 'Iyandikishe kuri WhatsApp', cta2: 'Reba amasomo', coursesT: 'Amasomo yacu 10', coursesS: 'Amasomo afatika agufasha kubona akazi cyangwa kwikorera.', pick: 'Hitamo iri somo',
    whyT: 'Impamvu PASCAL?', why: [['🎓', 'Turiga', 'Ubumenyi bufatika'], ['🛠️', 'Tugakora', 'Dukora imyitozo nyakuri'], ['🤝', 'Tukahuza', 'Duhuza abanyeshuri n’amahirwe'], ['🌱', 'Dukura', 'Dukura hamwe ubumenyi n’icyizere']],
    gain: 'Icyo uzunguka', gains: ['Ubumenyi bufatika', 'Amahirwe yo kubona akazi', 'Kwikorera', 'Guhuzwa n’amahirwe'],
    galT: 'Ubuzima kuri PASCAL', applyT: 'Iyandikishe', applyS: 'Uzuza ifishi — ubusabe bwawe bufungurwa kuri WhatsApp, witeguye koherezwa.',
    f: { name: 'Amazina yombi', gender: 'Igitsina', m: 'Gabo', fm: 'Gore', dob: 'Itariki y’amavuko', phone: 'WhatsApp / telefone', email: 'Imeri (si ngombwa)', loc: 'Akarere / Umurenge', edu: 'Amashuri wize', pickC: 'Amasomo ushaka (3 ntarengwa)', msg: 'Ubutumwa (si ngombwa)', consent: 'Nemeye ko mpamagarwa ku busabe bwanjye.', send: 'Ohereza ubusabe kuri WhatsApp', req: 'Ni ngombwa', badPhone: 'Shyiramo nimero y’u Rwanda nka 0788 123 456', pickOne: 'Hitamo isomo rimwe nibura', ok: 'Ubusabe bwawe burateguye!', okS: 'WhatsApp igomba gufunguka. Niba bidakunze, kanda hasi.', again: 'Fungura WhatsApp', newApp: 'Ubusabe bushya', ref: 'Nomero' },
    edus: ['Amashuri abanza', 'Icyiciro rusange (S1–S3)', 'Icyiciro cya kabiri (S4–S6)', 'TVET / Diploma', 'Kaminuza', 'Ibindi'],
    contactT: 'Udusure cyangwa Utwandikire', loc: 'Aho tuherereye', call: 'Twohamagara', rights: 'Uburenganzira bwose burabitswe.', quote: 'Ejo hazaza hawe hatangirira ku bumenyi bumwe bufatika.' },
  fr, sw,
}
